/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GoogleGroupsRouteImport } from './routes/google-groups'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as BetaIosRouteImport } from './routes/beta-ios'
import { Route as BetaAndroidRouteImport } from './routes/beta-android'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as PrayerCirclesInviteCodeRouteImport } from './routes/prayer-circles.invite.$code'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleGroupsRoute = GoogleGroupsRouteImport.update({
  id: '/google-groups',
  path: '/google-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaIosRoute = BetaIosRouteImport.update({
  id: '/beta-ios',
  path: '/beta-ios',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaAndroidRoute = BetaAndroidRouteImport.update({
  id: '/beta-android',
  path: '/beta-android',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrayerCirclesInviteCodeRoute = PrayerCirclesInviteCodeRouteImport.update({
  id: '/prayer-circles/invite/$code',
  path: '/prayer-circles/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta-android': typeof BetaAndroidRoute
  '/beta-ios': typeof BetaIosRoute
  '/download': typeof DownloadRoute
  '/google-groups': typeof GoogleGroupsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/tos': typeof TosRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/prayer-circles/invite/$code': typeof PrayerCirclesInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta-android': typeof BetaAndroidRoute
  '/beta-ios': typeof BetaIosRoute
  '/download': typeof DownloadRoute
  '/google-groups': typeof GoogleGroupsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/tos': typeof TosRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/prayer-circles/invite/$code': typeof PrayerCirclesInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta-android': typeof BetaAndroidRoute
  '/beta-ios': typeof BetaIosRoute
  '/download': typeof DownloadRoute
  '/google-groups': typeof GoogleGroupsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/tos': typeof TosRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/prayer-circles/invite/$code': typeof PrayerCirclesInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta-android'
    | '/beta-ios'
    | '/download'
    | '/google-groups'
    | '/privacy'
    | '/support'
    | '/tos'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/prayer-circles/invite/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta-android'
    | '/beta-ios'
    | '/download'
    | '/google-groups'
    | '/privacy'
    | '/support'
    | '/tos'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/prayer-circles/invite/$code'
  id:
    | '__root__'
    | '/'
    | '/beta-android'
    | '/beta-ios'
    | '/download'
    | '/google-groups'
    | '/privacy'
    | '/support'
    | '/tos'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/prayer-circles/invite/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaAndroidRoute: typeof BetaAndroidRoute
  BetaIosRoute: typeof BetaIosRoute
  DownloadRoute: typeof DownloadRoute
  GoogleGroupsRoute: typeof GoogleGroupsRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TosRoute: typeof TosRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  PrayerCirclesInviteCodeRoute: typeof PrayerCirclesInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-groups': {
      id: '/google-groups'
      path: '/google-groups'
      fullPath: '/google-groups'
      preLoaderRoute: typeof GoogleGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-ios': {
      id: '/beta-ios'
      path: '/beta-ios'
      fullPath: '/beta-ios'
      preLoaderRoute: typeof BetaIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta-android': {
      id: '/beta-android'
      path: '/beta-android'
      fullPath: '/beta-android'
      preLoaderRoute: typeof BetaAndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-circles/invite/$code': {
      id: '/prayer-circles/invite/$code'
      path: '/prayer-circles/invite/$code'
      fullPath: '/prayer-circles/invite/$code'
      preLoaderRoute: typeof PrayerCirclesInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaAndroidRoute: BetaAndroidRoute,
  BetaIosRoute: BetaIosRoute,
  DownloadRoute: DownloadRoute,
  GoogleGroupsRoute: GoogleGroupsRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TosRoute: TosRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  PrayerCirclesInviteCodeRoute: PrayerCirclesInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
